---
title: "Web Scraping"
author: "Ahmed Elsaeyed"
date: "3/17/2022"
output:
  html_document:
    df_print: paged
    fig_caption: true
    css: ae_theme.css
    theme: cosmo

---

1.
## Setting Up Libraries
I will mainly be using tidyr and dplyr here to do the analysis.

```{r setup, include=FALSE}

knitr::opts_chunk$set(class.source = "codechunk")
library(tidyr)
library(dplyr) 
library(RCurl)
library(ggplot2)
library(XML)
library(jsonlite)


```

2.
## Goal
Pull in book information for three books, each in a different format - XML, JSON, and HTML. I will put the data on my github and read them in using getURL. 

3.   
## The XML   
```{r xml url }
my_git_url <- getURL("https://raw.githubusercontent.com/aelsaeyed/Data607/main/LAB6/books.xml")
#booksXML <- xmlToDataFrame(my_git_url)
booksXML <- xmlToList(my_git_url)
booksXML
```
4.   

## The JSON
```{r json url }

my_git_url <- getURL("https://raw.githubusercontent.com/aelsaeyed/Data607/main/LAB6/books.json")

booksJSON <- jsonlite::fromJSON( my_git_url)
booksJSON

```
5. 
## The HTML
```{r html url }
my_git_url <- getURL("https://raw.githubusercontent.com/aelsaeyed/Data607/main/LAB6/books.html")
booksHTML <- readHTMLTable(my_git_url, which=1)
booksHTML
```





